### ISSUE TITLE
Dative subject

### ISSUE THREAD

**Issue by PhyloStar** [PhyloStar/UDTelugu#1]
Marking dative subject in Telugu. Example:
naaku oka ruupaayi kaawaali

naaku is first person singular + dative. Is it a nsubj or a obj?

@viswanath says it is a nsubj whereas Hindi Treebank marks it as obj.

**Comment by nishkalavallabhi** [comment]
I think naaku is nsubj, and (oka rupayi) is the dobj for kaawaali. But this seems to be like a reverse process: thinking in English and writing in Telugu!!

**Comment by PhyloStar** [comment]
In a recent paper, Croft pointed dative subjects which seem like objects due to dative suffix: 
[croft_invited_talk_2.pdf](https://github.com/PhyloStar/UDTelugu/files/1135386/croft_invited_talk_2.pdf)

**Comment by nishkalavallabhi** [comment]
what should we do about this sentence? 
I just skimmed through the Croft reading, it seems to me that naaku is a subject and rupaayi is an object? There is no suffix for rupaayi too.

**Comment by PhyloStar** [comment]
Yeah. I will keep the thread open so that we can have further discussions on this topic as we annotate mors sentences.

**Comment by PhyloStar** [comment]
http://ccat.sas.upenn.edu/plc/tamilweb/book/chapter3/node39.html

**Comment by PhyloStar** [comment]
https://github.com/UniversalDependencies/docs/issues/248#issuecomment-182121683

**Comment by PhyloStar** [comment]
https://github.com/UniversalDependencies/docs/issues/452

**Comment by PhyloStar** [comment]
http://ling.uni-konstanz.de/pages/home/butt/main/papers/nijmegen-hnd.pdf

After today's discussion with @nishkalavallabhi we decided to add a deprel nsubj:dat which is in spirit similar to Persian's nsubj:nc (non-canonical).

**Comment by PhyloStar** [comment]
Another useful comment:
http://ling.uni-konstanz.de/pages/home/butt/main/papers/nijmegen-hnd.pdf

**Comment by PhyloStar** [comment]
Another thesis on south dravidian languages:
http://linguistics.berkeley.edu/~mikkelsen/nizar_thesis.pdf

**Comment by PhyloStar** [comment]
http://web.mit.edu/rbhatt/www/24.956/dative.pdf
