### ISSUE TITLE
compound nouns

### ISSUE THREAD

**Issue by nishkalavallabhi** [PhyloStar/UDTelugu#10]
I did not realize there is a "compound" dependency.
I think these "kooragayala dukaanam", "pustakala beeruva" etc should be tied by a "compound" dependency relation, not tied by a nmod relation.  What do you think?

**Comment by PhyloStar** [comment]
There is an example of chair's  office that is simply a nmod because office can exist without chair's. Also, the word dont have equal status such as **raamuDikii, siitakii panDu iccanu**
