### ISSUE TITLE
use of "case" relation

### ISSUE THREAD

**Issue by nishkalavallabhi** [PhyloStar/UDTelugu#11]
My understanding of "case" relation is that we should use it for post-positions and the likes in Telugu. UD documentation also seems to say the same: "The case relation is used for any case-marking element which is treated as a separate syntactic word (including prepositions, postpositions, and clitic case markers). Case-marking elements are treated as dependents of the noun or clause they attach to or introduce."

In some examples, e.g., 9.1,
meem iNTiki weLLEEm

iMTiki is actually the object of weLLEEM and "ki" would have been connected to "iMTi" with a "case" relation. However, since "iNTiki" is a single word here, I think the relation is not case.. but obj. There are some such examples in 9.1. 

Take sentence 9: here, Sitaku is has a object relation with head, not case. I think this is the right annotation.

**Comment by PhyloStar** [comment]
Did I mark case? The old relation is gone now. :(
Do you think siitaku is a non-core argument? If it is a core argument, then, **siitaku** is obj. Have to change the relation.

**Comment by nishkalavallabhi** [comment]
I think Siitaku is a core arguement in that example.

**Comment by PhyloStar** [comment]
Yeah. All core arguemnts are obj whereas obl is mainly for denoting nominals with case markers such as instrumental, locative, allative.

**Comment by nishkalavallabhi** [comment]
oh, okay. got it now.
