### ISSUE TITLE
ewaru - pronoun, instead of determiner

### ISSUE THREAD

**Issue by nishkalavallabhi** [PhyloStar/UDTelugu#3]
Words like ewaru (who), ekkada (where) - shouldn't they be determiners?
They are Pronouns in English, and I saw that such words (yār for who) were tagged PRON in Tamil UD too.

**Comment by PhyloStar** [comment]
I think I marked them in the beginning as pronouns. Then, shifted to determiners especially as in:
interrogative determiners: which as in “Which car do you like?” (http://universaldependencies.org/u/pos/all.html#al-u-pos/DET)

It has to be uniform throughout.

**Comment by PhyloStar** [comment]
Okay. It is resolved and prounouns related to humans are tagged as PRON.
