### ISSUE TITLE
cowka - adjective or noun

### ISSUE THREAD

**Issue by nishkalavallabhi** [PhyloStar/UDTelugu#6]
If there is a sentence like "adi cowka" (It is cheap), should we consider it as a noun? or adj?

**Comment by PhyloStar** [comment]
I think it is adjective. Then, adi is dependent with a relation amod...

**Comment by nishkalavallabhi** [comment]
Okay, great. You tagged adi as DET and cowka as Noun :-) I think we can resolve this issue.
