### ISSUE TITLE
How should we treat a negation?

### ISSUE THREAD

**Issue by nishkalavallabhi** [PhyloStar/UDTelugu#8]
Some negations are tagged as verbs in the current annotations.
But are they? Since the negation words are closed class, may be we should choose AUX, or PART? 
in English, they seem to consider "not" as PART (Predicate negation: not, n’t, nt) but rest seem to go into ADV (no examples given). in Tamil, "illai", the word for "ledu" in Telugu is tagged as AUX. 

Additionally, I think negation should have a neg (negation modifier) relationship with the noun it is negating. (http://universaldependencies.org/docs/u/dep/neg.html) However, I don't find it in the list of relationships in the annotation interface. So, I tagged it as nmod for now.

**Comment by PhyloStar** [comment]
Which verb is it? ledu is a full verb that is a special feature of Telugu (dravidian languages) and Uralic languages. I dont know why it should be auxillary in Tamil.
The case of **kaadu, kaaru, kaawu** are particles.
For instance, in ENglish,
2       he      he      PRON    PRP     Case=Nom|Gender=Masc|Number=Sing|Person=3|PronType=Prs  5       nsubj   _       _
3       or      or      CCONJ   CC      _       4       cc      _       _
4       she     she     PRON    PRP     Case=Nom|Gender=Fem|Number=Sing|Person=3|PronType=Prs   2       conj    _       _
5       did     do      VERB    VBD     Mood=Ind|Tense=Past|VerbForm=Fin        11      advcl   _       _
6       not     not     PART    RB      _       5       advmod  _       SpaceAfter=No

not is treated as particle.
Is the negative modifier there in UDv2? I cant find it.

**Comment by nishkalavallabhi** [comment]
Why is ledu a verb but kadu a particle?
In the example I had, it was kadu I think.

**Comment by PhyloStar** [comment]
Where is the example?
**ataDu maa tammuDu kaadu**

I think that kaadu modifies tammuDu wheres ledu acts as non-existential verb for a subject. What do you think?

**Comment by PhyloStar** [comment]
Here is a WALS analysis on negation in the world's languages.
http://wals.info/chapter/112
The negative verb **leedu** is auxillary since it occurs with a main verb. @nishkalavallabhi 's the right way to go since **leedu** acquires the agrees with subject/object as the main verb does. This agreement differs. For example,

> atanu aameni eemi ceyyale**du**
In this case, ceyyaledu agrees with the object **aameni**

> neenu uriloo le**nu**
In this case, leenu inflects with subject.

But take, kaaru, kaadu, kaaDu which is not auxillary.  Or is it an auxillary?

**Comment by nishkalavallabhi** [comment]
Okay, shall we close this issue, now that we decided to treat negation words as verbs if they appear by themselves and as AUX if they appear with another verb?

**Comment by PhyloStar** [comment]
As of now I am tagging all negative verbs as VERB. Whenever, it occurs with another verb, I am calling it a serial verb construction. I also added this to AUX_.md page to be clear.
